### ISSUE TITLE
npm install | Node install bash : command not found

### ISSUE THREAD

**Issue by Minionjosh** [amzn/alexa-avs-raspberry-pi#96] opened 2016-04-04 11:49 UTC
when I try to do step 5 with the directory being the in the companion service and when I do the npm install command I get command not found and when I do the node -v [what was said in a different issue] I get a error that looks like this : https://gyazo.com/d910290c9d31f30448ea3920c36c2d62 but when I do the -v I get this https://gyazo.com/3b746cd768d6052bc268e3e3d5f0bd52 I tried doing it by doing node install but then it gave me this garbled mess [I'm a utter noob at this]https://gyazo.com/f92ca04cad673b20cc86be5acffb2f78 .

Is this because I'm using the Pi 1 [using the pi one while I wait for the funds for the pi 3] or because I'm dum and forgot some thing.

Thanks

Minion

**Comment by AndyW7** [comment] 2016-04-04 12:13
Hi Minion

I had the same problem at step 5 as was using RPI 2 B. I installed node.js following the guide at http://weworkweplay.com/play/raspberry-pi-nodejs/ follow step 2 and it installs the node.js that works on your version of the rpi. 

Once you get it installed it should work from then on, hope you get it sorted

**Comment by Minionjosh** [comment] 2016-04-04 12:17
I have just tried that and when I do the second command I get this https://gyazo.com/b6aa1086de1ba627df9d7308f3627ef9

**Comment by AndyW7** [comment] 2016-04-04 15:26
What happens when you type 
node -v
It should display what version your running/if nodes installed.

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Apr, 2016 at 13:18, Minionjosh<notifications@github.com> wrote:   
I have just tried that and when I do the second command I get this https://gyazo.com/b6aa1086de1ba627df9d7308f3627ef9

**Comment by AndyW7** [comment] 2016-04-04 15:39
Looking at your 3rd screenshot in your op you input 'node install' when the guide says npm install

**Comment by jpalat** [comment] 2016-04-04 23:17
The latest Raspian image comes with a version of node, but it does not install npm.  You can install npm with 
`sudo apt-get install npm` 

After that you should be able to run those commands.

**Comment by Bedour** [comment] 2016-04-05 16:21
Hey @AndyW7 

I had problems installing nodejs because it would throw segmentation fault error at me. So I took your advice and read the installation guide at weworkweplay and it fixed it! Now I'm struggling with `npm isntall` as it throws segmentation fault error. Do you know a way to solve it? My version of node is v4.2.1.

**Comment by AndyW7** [comment] 2016-04-05 16:44
Hi Bedour

A segfault could be caused by not changing directory first make sure you have changed the directory to,

cd <REFERENCE_IMPLEMENTATION>/samples/companionService

Also npm install is spelt wrong,
Hope that works

**Comment by Bedour** [comment] 2016-04-05 16:52
Yes I am in the right directory, and the above was just a typo.

You'll never believe what happened, I typed `npm instal` (with 1 L) and it worked!
![image](https://cloud.githubusercontent.com/assets/5548810/14290488/2aa95d9e-fb57-11e5-9beb-c108c1310b2b.png)

Thanks for your help anyway!

**Comment by AndyW7** [comment] 2016-04-05 16:55
Glad you got it sorted and good luck with your project

**Comment by ajotwani** [comment] 2016-04-13 17:35
Closing as resolved.

**Closed by ajotwani** 2016-04-13 17:35 UTC
Labels: node, npm

**Comment by malwareoverflow** [comment] 2018-07-29 16:43
if you are using debian see my answer here

https://stackoverflow.com/questions/48943416/bash-npm-command-not-found-in-debian-9-3#51582412
