### ISSUE TITLE
Walkthrough is problematic for Raspian Jessie

### ISSUE THREAD

**Issue by RadianM** [amzn/alexa-avs-raspberry-pi#35] opened 2016-03-27 22:18 UTC
Wheezy was superseded by Jessie last July. Most noobs doing a clean Raspian installation in 2016 will be working with Jessie which already has Java and will begin to run into trouble as early as step 2.5
Some advice that expands on what to do if the following is not the case would be very helpful

> Verify Node isn't already installed. It should print 'command not found'.

I've skipped the step and have got java V1.8.0_65 node V4.4.0 and npm  V3.8.3 yet I'm unable to start the server (npm start) with these errors:
![screenshot 2016-03-27 23 16 42](https://cloud.githubusercontent.com/assets/13075243/14068149/3a11d4dc-f472-11e5-8fff-5f6e11960174.png)

**Comment by Bantammenace** [comment] 2016-03-27 23:35
fyi I got it running on RPi 3 with Jessie with the latest update and upgrade earlier today. I followed the guide at 2.5  but at 2.6 I could not change the default even though I tried a couple of times. It didn't seem to matter and I think later on a more up to date version gets installed in any event. I also found issue #19 which may be the source of your woes.

**Comment by MrJamesEllis** [comment] 2016-03-28 05:14
I got it running on a RP 2 / Jessie which had Java already installed. It didn't like the openjdk 8 installed - wouldn't supply the provision URL at Step 10.

Removing openjdk 8 and Installing Java as specified at 2.6  (1.8.0_77) helped out with getting past that. The only oddity was that the instructions show you installing Java twice at Step 2.6 and Step 9 (./install-java8.sh) but I did it anyway.

Other versions:
Node: 5.9.0
NPM: 3.7.3

**Comment by RadianM** [comment] 2016-03-28 14:33
I have removed jdk and reinstalled 1.8.0_77 and tracked down my typo in config.js that prevented the server from starting. So now I've got the Companion service reporting that it's listening on port 3000.

However, when I exec the voice service client it doesn't offer the dialogue box shown in step 10 "Please register your device by visiting the following website..." but goes straight to the "Start listening" control panel (with an empty Bearer Token field). The terminal repeats the error "There was a problem connecting to the Companion Service..."

Guessing that something got out of sequence I tried starting over with a fresh SD card but after all that I end up in the same place. Some interaction with the AWS site were not possible to redo without deleting the app - I guess I'll have to try that next.

**Comment by RadianM** [comment] 2016-03-28 20:31
OK I found the issue was with my javaclient/ssl.cnf file. The commonName field somehow got corrupted when I edited in countryName etc. Having restored the field I now get the registration link. If anyone has a similar issue - check your  ssl.cnf file.

I'm still not 100% sure what the syntax ought to be - e.g.what the # CN= etc. items are at the end of each line are for and if they're needed. I left the one at the end of the commonName field which obviously was meant to be left alone, but the other fields just have my details and it all seems ok anyway.

**Comment by chasedg2008** [comment] 2016-03-28 20:54
did you have to redo the certs?

**Comment by RadianM** [comment] 2016-03-28 21:32
I'm sorry, I really can't remember - It's been a long day!

**Comment by bill-orange** [comment] 2016-03-28 21:39
Can someone (redacting anything sensitive) post a correct ssl.cnf file?

**Comment by ajotwani** [comment] 2016-03-28 22:35
@RadianM @bill-orange here's what the ssl.conf file would look like, replacing country, state, locality with your respective info - https://gist.github.com/ajotwani/a0d54110a968c984fd0b

**Comment by bill-orange** [comment] 2016-03-29 00:55
Got it!  I messed it up by assigning a common name/

**Comment by rflook** [comment] 2016-04-04 22:03
I am also having this problem. I have double and triple checked my ssl.cnf file, even going so far as to copy the linked version above (and regenerated my keys) but to no avail. The only thing I have done differently from the guide is to use jdk 8.071 the soft float version of 77 doesnt seem to be on the oracle page (unless I am going mental???)

**Comment by ajotwani** [comment] 2016-04-13 17:34
Added an FAQ for "Companion Service" errors. See https://github.com/amzn/alexa-avs-raspberry-pi#cannot-connect-to-the-companion-service-errors

**Comment by bmcder01** [comment] 2016-05-09 04:09
I have managed to get to the same point described by @RadianM and @rflook; i.e. the listening dialogue comes up without asking to register and obtain the appropriate bearer token. Like @rflook I cannot see a problem with the ssl.cnf file. Has anyone got any further with this problem? Thanks.

**Comment by southpaw12590** [comment] 2016-06-08 07:24
I was getting this exact same error, a listening dialog with "There was a problem connecting to the Companion Service. Trying again in 2 seconds.  Please make sure it is up and running." repeating endlessly in the terminal, and no information dialog box with the localhost web address.  My ssl.conf file was correct, as were all my keys.  I realized I was starting the listening service as root by using "sudo npm start" in [...]/samples/companionService/ because I'd had to use sudo before in order to get something to install or configure correctly.  Once I used "npm start" instead, the URL popped up and everything worked perfectly.  Hope this helps.

**Comment by bmcder01** [comment] 2016-06-09 04:27
...thanks @southpaw12590 but running the listening service in root doesn't seem to be the cause of things not working for me. Went through it again and am still getting the same 'trying again in 2 seconds'. Clutching at straws, but I'd be interested in seeing your ss.conf file.

mine looks like the following at the moment.
=====================================================
[req]
distinguished_name      = req_distinguished_name
prompt                          = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName                 = theshack                                   # CN=
countryName                   = AU                                            # C=
stateOrProvinceName     = SA                                            # ST=
localityName                    = Blackwood                               # L=
organizationName           = OneMyallShack                       # O=
organizationalUnitName  = HomeAutomation                    # OU=

==================================================

**Comment by southpaw12590** [comment] 2016-06-09 04:47
@bmcder01, looking at your ssl.conf file, I can already notice that you shouldn't have changed the commonName value.  I've read several other posts where that was the problem.  Here's my ssl.conf file for comparison:

[req]
distinguished_name      = req_distinguished_name
prompt                  = no

[v3_req]
subjectAltName          = @alt_names

[alt_names]
DNS.1                   = localhost
IP.1                    = 127.0.0.1
IP.2                    = 10.0.2.2

[req_distinguished_name]
commonName              = $ENV::COMMON_NAME                 # CN=
countryName             = US                 # C=
stateOrProvinceName     = TX            # ST=
localityName            = CS                         # L=
organizationName        = NA                 # O=
organizationalUnitName  = NA          # OU=

I'd recommend changing everything under [req_distinguided_name] to a 2-letter code, just in case, I'm not sure which ones absolutely have to be that way, but I felt it was better to be safe than sorry.  With the exception of commonName, of course.

**Comment by bmcder01** [comment] 2016-06-09 05:07
...thanks again @southpaw12590. I had the ssl.conf as given in the instructions for this project when I was first trying to get it working. When I had no success I looked into what an ssl.conf is meant to look like and the version i showed above I believe complies with what is required. I think the $ENV::COMMON_NAME is meant to pick up a session variable, which means if one isn't set it doesn't matter. In any case, I had another go with the ssl.conf very similar to yours, but still get the 'trying again'.

**Comment by southpaw12590** [comment] 2016-06-09 05:54
@bmcder01 I'm sorry to hear that it didn't work.  At this point, I think I can only suggest recreating your keys with generate.sh, posting your [...]/companionService/config.js file so we can look for typos, and re-running npm install.  I say this because  It seems to me that your problems would lie with the listening server, since you're able to run the client without issues up until the connecting process.

**Comment by ajotwani** [comment] 2016-08-01 21:11
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Closed by ajotwani** 2016-08-01 21:11 UTC
Labels: companion service, java, ssl.cnf
