### ISSUE TITLE
alexa not giving output

### ISSUE THREAD

**Issue by Ikol18** [amzn/alexa-avs-raspberry-pi#163] opened 2016-04-25 14:44 UTC
Everything is setup perfectly with oracle java 8, maven ,node and everything
When I click on start listening the bar indicates its listening but when I press stop its not giving output
please help me
useful info:
using rpi2
usb sound card with mic input and speaker output(both are in working condition)
node v 5.10.0 and npm v3.8.3

**Comment by picmax** [comment] 2016-04-28 05:12
I think I have the same issue wiht my USB sound card. The speaker and mic works. After I hit Start Listening button, I can send command to Alexa. For example, if  I say "Play KBSX" and it starts to play the radio fine. The problem is I cannot hear the audio cue and the voice from Alexa. I used to be able to hear that when I have a separate USB mic and audio in the 3.5mm socket.

Any idea?

**Comment by Ikol18** [comment] 2016-04-28 18:11
No still facing same issue

**Comment by samknight** [comment] 2016-04-28 21:18
@Ikol18 can you hear the audio cue? and when you speak does the bar on the javaclient move?

Try plugging in headphone to the 3.5mm jack and forcing audio through that as described in the readme

**Comment by picmax** [comment] 2016-04-29 02:43
@samknight I can hear audio stream, for example, radio stream sent by Alexa fine. However I cannot hear what Alexa says. When it worked before, she would say "Playing KBSX from Tunin" after I speak "Play KBSX". Now there are just pulses then the radio starts to play.

**Comment by samknight** [comment] 2016-04-29 07:23
Sorry @picmax , that one has stumped me.

**Comment by Ikol18** [comment] 2016-04-29 17:39
@samknight When I click on start listening the bar starts moving as if its listening but when I press stop I don't get any response

**Comment by picmax** [comment] 2016-04-29 19:26
If I ask Alexa for news update I can hear part of Alex's response before the news update. It seems the responses got cut off.

**Comment by picmax** [comment] 2016-04-30 01:03
See this for a fix: #156

**Comment by Ikol18** [comment] 2016-04-30 10:16
@picmax  thanku so much its working now..but how do I get the amazon music onto it

**Comment by swasey-amzn** [comment] 2016-05-06 21:25
To get Amazon music you'll have to have created your AVS product as a Device in the online tool. There are two options: "Device" and "Application". Applications can not have Amazon music. However, Devices are able to request Amazon Music. If you created your product as a Device and you did NOT request Amazon Music when registering, you can go back and request it in the tool. If you created your product as an Application then you'll need to follow the steps again and create a brand new product as a Device. The instructions on the README for this repository show you how to create a Device and call out that you can request Amazon Music.

**Comment by ajotwani** [comment] 2016-05-16 18:10
Closing as resolved.

**Closed by ajotwani** 2016-05-16 18:10 UTC
Labels: sound/microphone

**Comment by TheIncompleteCoder** [comment] 2017-06-20 06:18
i am having the same issue.
just use rpi  3.5 mm jack instead of usb adapter.

**Comment by stappjno** [comment] 2017-10-26 10:37
I'm having the same issue as TheIncompleteCoder (RPi3 Model B). USB-Mic + 3.5mm portable Speakers.
In the 3 console Windows everything looks well.
In the java-app I see the mic-Bar, Wakeword also works.
Playing a Radio Station also works, I think just the first 10-20 Seconds are not sent to the speaker. Has anyone found a Solution for this?

**Comment by nekhil** [comment] 2018-02-09 17:38
I have installed alexa in the raspberry pi 3.When i pressed the mic button,said something i can hear the beep sound,but the alexa is not responding.The log is empty.......................................
The speakers are seperately connected to 3.5mm audio jack of raspberry pi 3 and the mic is connected to the sound card.(The sound card is working fine,i have recorded my audio and played it)
any one please help me.........??????
