### ISSUE TITLE
Alexa stops to listen immediately

### ISSUE THREAD

**Issue by NicolaGenesin** [amzn/alexa-avs-raspberry-pi#39] opened 2016-03-28 00:44 UTC
1. Node server is listening correctly on 3000
2. Java client is working correctly
3. Bearer token is correctly fetched through the provision url
4. Press Start Listening

What happens here is that **the client stops listening immediately after the beep sound** (shows "Processing" state for a few milliseconds and then the button return to the state "Start Listening").

- I am using headphones and forcing the audio to the 3.5 mm via raspi-config.
- I am using Razer Chroma 7.1 microphone (I was successfully able to record a sample through arecord example.wav -D sysdefault:CARD=1)

**Comment by NShak** [comment] 2016-03-28 00:55
same problem here. Im using my tv as the audio out (HDMI) and a mini usb mic as input. I noticed if you lower the gain in alsamixer for both audio output and the mic, it helps a bit, but the problem is still there.

**Comment by jacksonrdlc** [comment] 2016-03-28 13:24
@NicolaGenesin So I had this same problem yesterday when I was setting it up and it turned out that I hadn't set up my microphone correctly yet in the Raspberry Pi OS. Assuming that you have your Pi connected to a monitor, go into the System or Audio configuration from the start menu dropdown and change the audio device to my microphone and click a checkbox saying that I'm using a microphone. Sorry, I'm not next to my Pi right now BUT this totally had to do with my Microphone not being set up correctly yet. Hard to know it wasnt in the Raspbian OS.

**Comment by NicolaGenesin** [comment] 2016-03-28 18:14
Done as you said (was not the default mic) but nothing changed (now it listen half a second more before stopping itself)

<img width="1303" alt="screen shot 2016-03-28 at 19 12 23" src="https://cloud.githubusercontent.com/assets/3284778/14085666/14dbbd02-f519-11e5-8ca1-806c513a7b42.png">

**Comment by bill-orange** [comment] 2016-03-29 01:52
Same thing here. I found maxing out the mike gain gave me enough time to blurt out a question.

**Comment by bill-orange** [comment] 2016-03-30 17:17
I have also noticed that Alexa stops listening too early.  Try this:

"Who was the third man to walk on the moon?"

Alexa answers with information about the movie "Third Man".  It will not listen long enough to catch the  phrase 'to the moon'.  Does anyone have an ECHO.  I would be useful to know if it answers correctly.

P.S. Charles Conrad

**Comment by gpetroski** [comment] 2016-03-31 05:05
You can open up javaclient/src/main/java/com/amazon/alexa/avs/AVSApp.java and change ENDPOINT_SECONDS to pad how long you want it to listen for. Run another 'mvn install' to recompile it. This appears to control how long it waits in silence before submitting the answer. It doesn't always guarantee a better response, but at least you feel like you can ask a full question. I was able to get her to tell me "Pete Conrad" one of the times I asked.

**Comment by bill-orange** [comment] 2016-03-31 14:48
I changed ENDPOINT_SECONDS from 2 to 7 seconds.  It works much better now.  I got the Pete Conrad answer on the first try.  Seven may be a bit much. I may try 5 later.

NicolaGenesin please try this change.  It worked for me.  It should work for you.

On a related topic, I have tried several microphones plugged into my usb sound device.  My Shure mic worked sorta ok. The best by far is the calibration microphone that came with my Onkyo NR-626 receiver.  I am a ham.  I have lots of mics to try!

**Comment by bill-orange** [comment] 2016-03-31 17:58
After some experimentation, I suggest:
ENDPOINT_THRESHOLD 6 
ENDPOINT_SECONDS 6

I believe this should be a Pull Request but others should test it first.  It may be very microphone dependent.

PS: the Onkyo calibration microphone really works great.

**Comment by bobmeister9** [comment] 2016-04-09 23:26
This is a reasonable work around for the demo, but it would be interesting to figure out why the silence at the end of the question can't be detected.  If I get some time, I'll take a look and post up what I find.

**Comment by ajotwani** [comment] 2016-05-16 17:51
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Closed by ajotwani** 2016-05-16 17:51 UTC
Labels: Alexa, enhancement, sound/microphone

**Comment by gigio68** [comment] 2017-02-14 16:04
I am trying to find a way to delay Alexa's response, as I can only hear "...xa" after I ask her name.
The workaround to change ENDPOINT_SECONDS and ENDPOINT_THRESHOLD was promising. However I cannot find these two variables anywhere throughout the code (javaclient/src/main/java/com/amazon/alexa/avs/AVSApp.java does  not include it as of today).
Is there any other constant that I can change?
Thanks!
