### ISSUE TITLE
alexa-avs-raspberry-pi error 

### ISSUE THREAD

**Issue by SyntaxErrr0r** [amzn/alexa-avs-raspberry-pi#110] opened 2016-04-07 01:41 UTC
I got it running once, had fun, worked great, cannot get it to run again 

![ss 2016-04-06 at 06 38 40](https://cloud.githubusercontent.com/assets/18282745/14337889/18b455dc-fc27-11e5-8150-af9f406c16bd.png)

**Comment by SyntaxErrr0r** [comment] 2016-04-07 08:59
Have double checked all the files make sure the information is correct, double checked client ID and everything and everything seems correct. Changed directories to companionService started npm , it shows the listening in 3000 , open new terminal cd to java client and run mvn. Not sure if im doing something wrong but can not get it to work again, and keep getting error. Any help appreciated, thanks!

**Comment by wedob13** [comment] 2016-04-08 20:33
after a lot of work to have a successful build and run with mvn exec i also got stumbled across this error

**Comment by ajotwani** [comment] 2016-04-12 03:13
@SyntaxErrr0r This is probably related to your microphone. Please see this thread https://github.com/amzn/alexa-avs-raspberry-pi/issues/117

**Comment by ajotwani** [comment] 2016-04-12 03:14
Closing as duplicate of https://github.com/amzn/alexa-avs-raspberry-pi/issues/117.

**Closed by ajotwani** 2016-04-12 03:14 UTC
Labels: duplicate
