### ISSUE TITLE
Fails at Step 9 on a new Pi v3 with 2016-03-18-raspbian-jessie.img

### ISSUE THREAD

**Issue by servebeer** [amzn/alexa-avs-raspberry-pi#65] opened 2016-03-29 21:45 UTC
I just tried to install this on my new Pi v3 running 2016-03-18-raspbian-jessie.img. I get all the way to Step 9, and it fails with:

Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] -------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------------------
[INFO] Total time: 33.858 s
[INFO] Finished at: 2016-03-29T16:32:49-05:00
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vlasov01** [comment] 2016-03-30 00:06
@servebeer Try to run with some debug information output:
mvn -e -X install
It may help understand the issue.

**Comment by KevinHanson** [comment] 2016-03-30 01:48
@servebeer I was getting the same generic error as this last night and after running the mvn -e I found the error was actually: "sslCleitnKeyStore is blank in you config file" And this was because at instruction 7 step 2 you have to really compare your config.json file to the screenshot they provide. I had not specified the sslClientKeyStore in my file and that is why I got the error that I saw. Look through the debug errors carefully. Maybe you are running into the same thing I did or not at all.

**Comment by servebeer** [comment] 2016-03-30 12:22
Running "mvn -e -X install" results in "BUILD SUCCESS". Running "man -e -X exec:exec" results in everything running fine. This doesn't make sense as I did;t make any changes except including the two switches. Oh well, I guess all that matters is that it works now. Any suggestions on how to make the auth tokens "sticky" so I don't have to regenerate them every time I reboot? I also saw a mention about ways to make voice recognition work, but I didn't see any step-by-step process for it.

Thanks!
Jon

**Comment by gregwa1953** [comment] 2016-03-30 12:31
@servebeer,
See issue #60 for an update on the questions you are having about tokens
and "active listening" for the wake word.

Greg

**Comment by servebeer** [comment] 2016-03-30 16:39
So I ran man without the switches, and the java interface comes up, but back at the console I do see two errors:

ERROR Null object returned for RollingFile in Appenders
ERROR Unable to locate appender file for logger

Then, when I click on "Listen", a java "Error" window opens with no text in it, just an "OK" button and a red "stop sign" with a "X" in it. I click on the "OK" button, and it appears to work. Back at the console, I do notice two other errors:

[AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occurred creating speech request java.lang.NullPointerException

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

These appear to be the only errors left.

**Comment by wedob13** [comment] 2016-03-31 10:07
i get an error too at the point. even when i try the manual switch it stills gives me a success build on install but a failure when i run do you a maven plugin

**Comment by dmarkscouk** [comment] 2016-03-31 19:53
I'm hitting the same problem with the last command in step 9 `man exec:exec`. I've tried all the suggestions above with no luck, and get:

`Error: Could not find or load main class com.amazon.alexa.avs.AVSApp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.957 s
[INFO] Finished at: 2016-03-31T19:35:17+00:00
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by phamhp** [comment] 2016-04-01 05:58
@servebeer @dmarkscouk  I got the same error when I run the command ' mvn -e -X exec:exec'. I noticed this error 'PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused' .
So i used the terminal in raspbian, export the 2 maven variables then ran the command again. Build success. Hope it helps.

**Comment by cwilkes** [comment] 2016-04-01 06:25
I had similar problems with `exec:exec` and after hours of screwing around I almost have it working.  I'm not sure what did and didn't work but here's some of my changes:

up the exec-maven-plugin from 1.2.1 to 1.4.0
change the alpn-boot version to 8.1.6.v20151105 as that's the one for oracle java 1.8.0_65-b17
I also upped the slf4j version to 1.7.20 and log4j to 2.5, but that's probably not needed

I'm surprised no one else ran into the problem of not being able to find libvlc.so and libvlccore.so which I fixed by symlinking the files from /usr/lib/ to /usr/lib/vlc .

@dmarkscouk you have to run with "-e -X" to get anything useful out of maven.  I typically run it like this: `mvn -X -e exec:exec >/tmp/f.1 2>/tmp/f.2` and then in another window do a `tail -f /tmp/f.1 /tmp/f.2`

**Comment by dmarkscouk** [comment] 2016-04-01 16:19
Thanks for your suggestions @phamhp @cwilkes, however neither of your suggestions have got me around this issue.

Any further help is much appreciated.

**Comment by servebeer** [comment] 2016-04-01 16:59
It would be nice if Amazon could supply a pre-built Pi image. That way, everything should work "out-of-the-gate" and all the end user would have to do is apply their person info to the config.

**Comment by MrMindlink** [comment] 2016-04-03 19:23
mvn validate - build success
mvn install - build failure

mvn -e -X install

pi@raspberrypi:~/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient $ mvn -e -X install

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.734 s
[INFO] Finished at: 2016-04-03T19:09:36+00:00
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project sample-java-client: /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/res/version.properties (Permission denied) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project sample-java-client: /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/res/version.properties (Permission denied)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/res/version.properties (Permission denied)
	at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:307)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/res/version.properties (Permission denied)
	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:129)
	at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:261)
	at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:301)
	... 22 more
Caused by: java.io.FileNotFoundException: /home/pi/Downloads/alexa-avs-raspberry-pi-master/samples/javaclient/target/classes/res/version.properties (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2202)
	at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:2170)
	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:114)
	... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vlasov01** [comment] 2016-04-03 20:08
@MrMindlink You can try to resolve permission problems or run the following:
`sudo mvn -e -X install`

**Comment by recklessfb** [comment] 2016-04-04 02:42
Can someone help me out here. I am very new to the pi environment. 
mvn validate was a success. 
mvn installl was also a success
but mvn exec-exec fails. 

mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Invalid token=STRING at (line no=9, column no=16, offset=282). Expected tokens are: [COMMA]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:238)
	at org.glassfish.json.JsonParserImpl.access$1200(JsonParserImpl.java:61)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:284)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:184)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:60)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:46)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:79)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:74)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.546 s
[INFO] Finished at: 2016-04-03T22:40:40-04:00
[INFO] Final Memory: 7M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
pi@raspberrypi:~/Downloads/alexa/samples/javaclient $

**Comment by vlasov01** [comment] 2016-04-04 03:29
@recklessfb It complains about the config file you've edited. Please double check content of your <REFERENCE_IMPLEMENTATION>/samples/javaclient/config.json (or list it here).

**Comment by wedob13** [comment] 2016-04-04 09:07
Hello, I get install success,validate success but when i run exec i get this

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.655 s
[INFO] Finished at: 2016-03-18T19:12:07+00:00
[INFO] Final Memory: 7M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by recklessfb** [comment] 2016-04-04 10:30
@vlasov01 Thanks. I will double check it this evening. (line no=9, column no=16, offset=282). Am I right to assume the culprit is located here? Or would it be anything after that?

**Comment by recklessfb** [comment] 2016-04-06 00:46
{
    "productId":"DV1",
    "dsn":"123456",
    "provisioningMethod":"companionservice",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":" /home/pi/Downloads/alexa/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"talktome"
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":" /home/pi/Downloads/alexa/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"talktome"
        "sslCaCert":" /home/pi/Downloads/alexa/samples/javaclient/certs/ca/ca.crt"
    }
}

**Comment by vlasov01** [comment] 2016-04-06 01:18
@recklessfb You are missing a comma after
`"sslKeyStorePassphrase":"talktome"`

You can validate your json online, for example at http://jsonlint.com/ .

As well you have extra space in the values of sslKeyStore, sslClientKeyStore and sslCaCert.
I think it is better to remove spaces.

**Comment by recklessfb** [comment] 2016-04-06 03:50
@vlasov01 Seems there was something wrong with my config.json file. Couldn't really get my hand on what exactly. I did add the comman and remove the extra space. I ended up re unzipping the config file and copied it over. I got it to work. 
Thanks a bunch.

**Comment by vlasov01** [comment] 2016-04-06 23:31
@recklessfb I'm glad that it is working for you!

**Comment by ajotwani** [comment] 2016-04-12 03:06
Closing as fixed.

**Closed by ajotwani** 2016-04-12 03:06 UTC
Labels: Maven, Pi 3

**Comment by jamrizzi** [comment] 2016-04-13 08:02
I'm having the exact same problem @wedob13 is having.

**Comment by wedob13** [comment] 2016-04-13 12:39
i got passed my build failures by installing fresh os again. double checking everything in private keys/public keys/keystore passphrase. I also set my correct timezone settings because i didnt have them and generated a certificate (some users reported this is also a problem).

**Comment by NilanjPatel** [comment] 2016-05-30 12:51
@vlasov01 my json file is correct still the error is "../home/pi/Downloads/alexa/samples/javaclient/certs/client/client.pkcs12" does not exist

please help me..

**Comment by ssfdre38** [comment] 2016-05-30 17:16
Its cause you need to go to /home/pi/Downloads/alexa/samples/javaclient and type chmod +x generate.sh and then ./generate.sh then type your product ID that you made on the alexa site and your serial number then it will make all the certs for you including client.pkcs12

**Comment by AdithyanI** [comment] 2016-10-11 21:29
@dmarkscouk Did you figure out a solution to your problem?

**Comment by dmarkscouk** [comment] 2016-10-12 08:40
@AdithyanI I just stared again and got there in the end. I'm not sure why I had the problem, but must have typed one of the instructions incorrectly.

**Comment by jolimk** [comment] 2016-12-08 22:40
I haven't solved the problem. Im stuck at this for days. PLEASE HELP

**Comment by c0deous** [comment] 2017-01-16 01:50
Solved for me by simply running under root privileges:
    sudo mvn -e -X install

**Comment by Vino-git** [comment] 2018-03-27 15:00
I am having the same problem when I execute this command in the raspberry console but its super working in putty that ssh to the same raspberry device....

Its weird  :)

Please help..

**Comment by Vino-git** [comment] 2018-03-27 19:12
I got it fixed with a simple command.

unset DISPLAY
